M48
; DRILL file {KiCad 9.0.0} date 2025-04-10T20:17:27-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-10T20:17:27-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
G00X74.712Y-63.0
M15
G01X75.412Y-63.0
M16
G05
G00X74.712Y-73.0
M15
G01X75.412Y-73.0
M16
G05
M30
